/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas5.gui.view;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class myGuihome extends javax.swing.JFrame {

    /**
     * Creates new form myGuihome
     */
    public myGuihome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        listPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cara = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        kontak = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        home2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        au2 = new javax.swing.JLabel();
        list2 = new javax.swing.JLabel();
        order2 = new javax.swing.JLabel();
        btnLogout2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Caprica Script Personal Use", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 202, 176));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Gift - 01.png")); // NOI18N
        jLabel1.setText("FaGiftbox");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 195, 36));

        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Close.png")); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 15, -1, -1));

        minimize.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Minimize-WF.png")); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 15, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 70));

        mainPanel.setBackground(new java.awt.Color(149, 165, 166));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(149, 165, 166));

        jLabel23.setFont(new java.awt.Font("Amplify Personal Use Only", 0, 36)); // NOI18N
        jLabel23.setText("SELAMAT DATANG");

        jLabel32.setFont(new java.awt.Font("Caprica Script Personal Use", 2, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 76, 144));
        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Instagram.png")); // NOI18N
        jLabel32.setText("@fagiftbox");

        jLabel35.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel35.setText("Aplikasi ini digunakan untuk memesan giftbox ");

        jLabel36.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel36.setText("Agan agan bisa memesan box dengan ukuran dan warna yg di inginkan looh");

        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel37.setText("Untuk detail lebih jelasnya agan dan Sista bisa cek di instagram kami");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel35))
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel36)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(homePanel, "card2");

        listPanel.setBackground(new java.awt.Color(255, 202, 176));

        jLabel24.setFont(new java.awt.Font("Amplify Personal Use Only", 2, 56)); // NOI18N
        jLabel24.setText("Oops!");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel25.setText("Bagian ini masih dalam tahap pengembangan");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel26.setText("Silahkan kembali lagi nanti");

        jLabel27.setFont(new java.awt.Font("Caprica Script Personal Use", 2, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 76, 144));
        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Instagram.png")); // NOI18N
        jLabel27.setText("@fagiftbox");

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                        .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(listPanelLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel26)))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(listPanel, "card3");

        cara.setBackground(new java.awt.Color(76, 191, 239));

        jLabel30.setFont(new java.awt.Font("Amplify Personal Use Only", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 76, 144));
        jLabel30.setText("Panduan Pemesanan");

        jLabel33.setFont(new java.awt.Font("Caprica Script Personal Use", 2, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 76, 144));
        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Instagram.png")); // NOI18N
        jLabel33.setText("@fagiftbox");

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel38.setText("1. Agan dan Sista memilih dahulu ukuran yang akan dipesan, ukuran bisa di costom juga looh");

        jLabel39.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel39.setText("2. Jika sudah memilih silahkan klik menu pemesanan untuk memasukkan detail dan klik order");

        jLabel40.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel40.setText("3. Done, pesanan Agan dan Sista akan di selesai dalam 2-7 hari tergantung kesibukan kami ");

        jLabel41.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel41.setText("4. Estiminasi pengiriman mulai dari 1 hari sampai 4 hari tergantung jauh dekat lokasi");

        jLabel42.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel42.setText("5. Agan dan Sista bisa menghubungin kami via contact yang ada di menu Contact");

        javax.swing.GroupLayout caraLayout = new javax.swing.GroupLayout(cara);
        cara.setLayout(caraLayout);
        caraLayout.setHorizontalGroup(
            caraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caraLayout.createSequentialGroup()
                .addGroup(caraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(caraLayout.createSequentialGroup()
                        .addGroup(caraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(caraLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel30))
                            .addGroup(caraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(caraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(caraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(caraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, caraLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(caraLayout.createSequentialGroup()
                                .addGroup(caraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        caraLayout.setVerticalGroup(
            caraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caraLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel30)
                .addGap(12, 12, 12)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel40)
                .addGap(13, 13, 13)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(cara, "card4");

        kontak.setBackground(new java.awt.Color(111, 190, 70));

        jLabel31.setFont(new java.awt.Font("Amplify Personal Use Only", 0, 36)); // NOI18N
        jLabel31.setText("Kontak Kami");

        jLabel34.setFont(new java.awt.Font("Caprica Script Personal Use", 2, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 76, 144));
        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Instagram.png")); // NOI18N
        jLabel34.setText("@fagiftbox");

        jLabel44.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas5/gui/view/asset/Chat-01-WF.png"))); // NOI18N
        jLabel44.setText("081214819389");

        javax.swing.GroupLayout kontakLayout = new javax.swing.GroupLayout(kontak);
        kontak.setLayout(kontakLayout);
        kontakLayout.setHorizontalGroup(
            kontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kontakLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(kontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31))
                    .addComponent(jLabel44))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        kontakLayout.setVerticalGroup(
            kontakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kontakLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        mainPanel.add(kontak, "card5");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 560, 450));

        menu.setBackground(new java.awt.Color(211, 84, 0));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        home2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas5/gui/view/asset/House-07.png"))); // NOI18N
        home2.setText("HOME");
        home2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        menu.add(home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 102, -1));
        menu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 134, 10));

        au2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        au2.setText("ABOUT ME");
        au2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        au2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                auMouseClicked(evt);
            }
        });
        menu.add(au2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 24, -1, -1));

        list2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        list2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas5/gui/view/asset/To Do List-WF.png"))); // NOI18N
        list2.setText("LIST UKURAN");
        list2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        menu.add(list2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, -1, -1));

        order2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        order2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas5/gui/view/asset/Mail  Next-WF.png"))); // NOI18N
        order2.setText("PEMESANAN");
        order2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        order2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });
        menu.add(order2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 202, -1, -1));

        btnLogout2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnLogout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas5/gui/view/asset/Logout.png"))); // NOI18N
        btnLogout2.setText("LOGOUT");
        btnLogout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        menu.add(btnLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 134, 38));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas5/gui/view/asset/Help - 01.png"))); // NOI18N
        jLabel28.setText("CARA ORDER");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        menu.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas5/gui/view/asset/Phonebook Search-WF.png"))); // NOI18N
        jLabel29.setText("CONTACT");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        menu.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        myGui n = new myGui();
        n.setVisible(false);
        this.setVisible(false);

        myGuihome h = new myGuihome();
        n.setVisible(true);

    }//GEN-LAST:event_btnLogoutMouseClicked

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked
        // TODO add your handling code here:
        orderView n = new orderView();
        n.setVisible(false);
        this.setVisible(false);

        myGuihome h = new myGuihome();
        n.setVisible(true);

    }//GEN-LAST:event_orderMouseClicked

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(listPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_listMouseClicked

    private void auMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_auMouseClicked
        // TODO add your handling code here:
        homeview n = new homeview();
        n.setVisible(false);
        this.setVisible(false);

        myGuihome h = new myGuihome();
        n.setVisible(true);
    }//GEN-LAST:event_auMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        

    }//GEN-LAST:event_homeMouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(cara);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(kontak);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jLabel29MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myGuihome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myGuihome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myGuihome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myGuihome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myGuihome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel au;
    private javax.swing.JLabel au1;
    private javax.swing.JLabel au2;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnLogout1;
    private javax.swing.JLabel btnLogout2;
    private javax.swing.JPanel cara;
    private javax.swing.JLabel close;
    private javax.swing.JLabel home;
    private javax.swing.JLabel home1;
    private javax.swing.JLabel home2;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel kontak;
    private javax.swing.JLabel list;
    private javax.swing.JLabel list1;
    private javax.swing.JLabel list2;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel menuPanel1;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel order;
    private javax.swing.JLabel order1;
    private javax.swing.JLabel order2;
    private javax.swing.JPanel utama;
    private javax.swing.JPanel utama1;
    private javax.swing.JPanel utama2;
    // End of variables declaration//GEN-END:variables
}
